config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users

  resources :users, only: [:index, :show]

  resources :articles
  resources :comments
  resources :gmaps

  root 'articles#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :comments
  belongs_to :user

  validates_presence_of :title, presence: { message: "can't be empty"}
  validates_presence_of :adress, presence: { message: "can't be empty"}
  validates_presence_of :user_id

  geocoded_by :adress
  #geocoded_by :adress, :latitude => :lat, :longitude => :lng
  after_validation :geocode, if: ->(article){ article.adress.present? and article.adress_changed? }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  paginates_per 10

  has_many :articles
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
        devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :current_password, :password_confirmation, :first_name, :last_name) }
      end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]
  #before_filter :require_user


  def index
    #@articles = Article.where(user_id:current_user.id)
    @articles = Article.order('created_at DESC').page(params[:page]).per(2)
    @hash = Gmaps4rails.build_markers(@articles) do |article, marker|
      marker.lat article.latitude
      marker.lng article.longitude
      marker.infowindow "#{article.title} #{article.resume}, #{article.adress}, #{article.user_id}"
      end
    #la map ne fonctionne plus depuis que j'ai ajouté ce truc de hash... Voir le modèle aussi
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
    # Access Current User
    @articles = current_user.articles
  end

  def create
    @article = Article.new(article_params)
    #@article.user_id = current_user
    article_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        @article.update_attributes!(:user_id => current_user.id)
        puts "-->#{@article.user_id}<--"
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
      @comments = @article.comments.all
      @comment = @article.comments.build

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :resume, :image, :user_id, :adress, :latitude, :longitude)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_name, :body, :article_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def full_name
    if self.first_name.blank?
      self.email
    else
      self.first_name
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  def index
    @articles = Article.page(params[:id]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_area :resume %>
  </div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<!-- GOOGLE MAP -->
<h1>Map with articles (Use the Zoom)</h1>
<div style='width: 100%;'>
 <div id="map" style='width: 100%; height: 400px;'></div>
</div>
<br />

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
</script>

<!-- END OF GOOGLE MAP -->

<h1>Listing Articles</h1>

<% if @articles %>

<div>
    <%= paginate(@articles) %>
    <%= page_entries_info @articles %>
    <ul>
        <% @articles.each do |p| %>
        <li>
            <h3><%= link_to p.title, article_path(p.id) %></h3>
            <p><small><strong>By:</strong> <%= p.user_id %></small></p>
            <p><%= p.resume %></p>
            <p><%= image_tag p.image_url(:thumb) if p.image? %></p>
            <% if user_signed_in? -%>
            <table>
              <tr>
            <td><%= link_to 'Show // ', p %></td>
            <td><%= link_to 'Edit // ', edit_article_path(p) %></td>
            <td><%= link_to ' Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          </table
            <% end -%>
        </li>
        <% end %>
    </ul>
    <%= paginate(@articles) %>
</div>


<% else %>
<p><%= puts "Il n'y a pas d'articles à afficher" %><p>

<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @article.resume %>
</p>


<p>
  <strong>Adress:</strong>
  <%= @article.adress %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@article.image_url, :width => 600) if @article.image.present? %>
</p>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    <%= f.hidden_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Article</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.article_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

<script>
    $('.alert').fadeOut(4000);
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p><%= link_to 'Administration', admin_session_path%> </p>
    <p class="copyright text-muted">Made with Rails // Simplon Prod 2015</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
  <h1>SHARE IT</h1>
  <h2>Partagez vos plus beaux souvenirs de vacances</h2>
  <div id="logo">
  <%= image_tag("logosimplonred.png", alt: "Logo de Simplon.co", :width => 150) %>
  </div>
</div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">

      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <%= link_to "Home", articles_path, class: 'navbar-brand' %>
            <% if user_signed_in? %>
            <p>Logged in as <strong><%= current_user.email %></strong></p>
              <% else %>
              <p>Welcome stranger</p>
            <% end %>
      </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                  <li><%= link_to 'My articles', articles_path %></li>
                  <li><%= link_to 'Members', users_path %></li>
                  <li><%= link_to 'New Article', new_article_path %></li>
                  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

                <% else %>

                  <li><%= link_to 'Posts', articles_path %></li>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Share it, just another blog !</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= render 'layouts/menu' %>
  <%= render 'layouts/flash_messages' %>

  <div class="container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

 <!-- Utilisé par Devise -->
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
<!-- fin -->


</body>
</html>

app/views/partials/_gmap.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
    <div class="users row">
        <% @users.each do |user| %>
        <div class="panel panel-default">
            <%= link_to user_path(user) do %>
            <div class="panel-body">
                <p>User ID : <%= user.id %></p>
                <p>First Name : <%= user.first_name %></p>
                <p>Last Name : <%= user.last_name %></p>
                <p>E-Mail : <%= user.email %></p>
            </div>
            <% end %>
        </div>
        <% end %>

    </div>
</div>


<h1>Listing Users, autre mise en forme</h1>

<table>
  <thead>
    <tr>
      <th>User ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate(@users) %>

app/views/users/show.html.erb
<div class="row profile">
    <div class="col-sm-4 col-md-3">

        <h1>Détails de l'utilisateur : <%= @user.first_name %>" "<%= @user.last_name %></h1>
        <ul>
          <%= content_tag(:li, ("First Name: " + @user.first_name)) unless @user.first_name.blank? %>
          <%= content_tag(:li, ("Last Name: " + @user.last_name)) unless @user.last_name.blank? %>
        </ul>
    </div>
    <div class="feed">
        <h3>Social Feed Coming</h3>
        <p>Put a couple of lines of text here and see how it scrolls</p>
    </div>
</div>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<div>
    <%= paginate(@articles) %>
    <%= page_entries_info @articles %>
    <ul>
        <% @articles.each do |p| %>
        <li>
            <h3><%= link_to p.title, article_path(p.id) %></h3>
            <p><small><strong>By:</strong> <%= p.user.email %></small></p>
            <p><%= p.resume %></p>
            <p><%= image_tag p.image_url(:thumb) if p.image? %></p>
            <% if user_signed_in? -%>
            <table>
              <tr>
            <td><%= link_to 'Show // ', p %></td>
            <td><%= link_to 'Edit // ', edit_article_path(p) %></td>
            <td><%= link_to ' Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          </table
            <% end -%>
        </li>
        <% end %>
    </ul>
    <%= paginate(@articles) %>
</div>